# -*- coding: utf-8 -*-
from typing import Mapping

from bring.mogrify import SimpleMogrifier


class InstallPkgMogrifier(SimpleMogrifier):

    _plugin_name: str = "install_pkg"

    _requires: Mapping[str, str] = {
        "folder_path": "string",
        "target": "string?",
        "merge_strategy": "dict?",
        "target_path_autogenerated": "boolean?",
    }
    _provides: Mapping[str, str] = {"folder_path": "string"}

    def is_ready(self) -> bool:

        pass
